---
permalink: migrate/migrate-to-latest-ontaptools.html 
sidebar: sidebar 
keywords: migrate 
summary: Ao migrar dados de storage, os back-ends de storage são integrados manualmente usando APIS REST. Ao migrar dados do provedor VASA, os dados são exportados do banco de dados Derby existente e importados para o banco de dados MongoDB. 
---
= Migrar das ferramentas do ONTAP para o VMware vSphere 9.x para o 10,3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao migrar dados de storage, os back-ends de storage são integrados manualmente usando APIS REST. Ao migrar dados do provedor VASA, os dados são exportados do banco de dados Derby existente e importados para o banco de dados MongoDB.


NOTE: Você deve migrar as ferramentas do ONTAP para a configuração do VMware vSphere 9.xx somente se a configuração estiver atendendo ao recurso do provedor VASA sozinho.


NOTE: Após a migração das ferramentas do ONTAP para o VMware vSphere 9.x para o 10,3, os armazenamentos de dados vVols com o protocolo NVMe/FC não funcionam porque o ONTAP Tools 10,3 oferece suporte apenas a NVMe-of com datastores VMFS.

*Sobre esta tarefa*

Você pode migrar das ferramentas do ONTAP para as versões do VMware vSphere 9.12D1 e 9.13D2 para o 10,3.


NOTE: Você deve pegar o backup OVA de sua versão atual antes de atualizar para as versões de patch.



== Etapas comuns de migração

. Implantar as ferramentas OVA para ONTAP para a versão do VMware vSphere 10,3.
. Adicione a instância do vCenter Server que você deseja migrar para as ferramentas do ONTAP para a versão do VMware vSphere 10,3. link:../configure/add-vcenter.html["Adicione instâncias do vCenter Server"]Consulte .
. Back-end de storage integrado localmente a partir das ferramentas do ONTAP para APIs de servidor do plug-in do VMware vSphere. Adicione o armazenamento como um armazenamento com escopo local para migração.
. Os armazenamentos de dados NFS e VMFS migrados das ferramentas do ONTAP para o VMware vSphere 9.xx ficam visíveis nas ferramentas do ONTAP para o VMware vSphere 10,3 somente após a ativação da tarefa de descoberta do datastore, o que pode levar até 30 minutos para ser acionada. Verifique se os armazenamentos de dados estão visíveis na página Visão geral das ferramentas do ONTAP para a página de interface de usuário do plug-in VMware vSphere.




== Etapas de migração do SRA

*Antes de começar*

Antes de migrar, certifique-se de que um dos sites está em um estado protegido e o outro está em um estado de recuperação.


NOTE: Não migre se o failover tiver sido concluído e a nova proteção estiver pendente. Complete a re-proteção e, em seguida, execute a migração. Depois de concluir o teste do plano de recuperação, limpe a recuperação do teste e inicie a migração.

. Execute as seguintes etapas para excluir as ferramentas do ONTAP para o adaptador SRA de versão do VMware vSphere 9.xx na interface de usuário do VMware Live Site Recovery:
+
.. Vá para a página de gerenciamento de configuração do VMware Live Site Recovery
.. Vá para a seção *Storage Replication Adapter*
.. Selecione o menu de elipse e selecione *Redefinir configuração*
.. Selecione o menu de elipses e selecione *Delete*
+
Execute estas etapas nos locais de proteção e recuperação.



. Instale as ferramentas do ONTAP para o adaptador VMware vSphere 10,3 SRA em locais de proteção e recuperação, usando as etapas em link:../protect/configure-on-srm-appliance.html["Configure o SRA no VMware Live Site Recovery Appliance"]
. Na página da interface de usuário do VMware Live Site Recovery, execute as operações *Discover Arrays* e *Discover Devices* e verifique se os dispositivos estão sendo exibidos como eram antes da migração.




== Etapas de migração do VASA Provider

. Ative A PORTA Derby 1527 nas ferramentas existentes do ONTAP para VMware vSphere. Para ativar a porta, faça login na CLI com o usuário raiz e execute o seguinte comando:
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. Implantar as ferramentas OVA para ONTAP para VMware vSphere 10,3.
. Adicione a instância do vCenter Server que você deseja migrar para as ferramentas do ONTAP para a versão do VMware vSphere 10,3. link:../configure/add-vcenter.html["Adicione uma instância do vCenter Server"]Consulte .
. Back-end de storage integrado localmente a partir das APIs de servidor do plug-in vCenter remoto. Adicione armazenamento como escopo local para migração.
. Emita a seguinte chamada de API para migrar:
+
[]
====
*Método HTTP e endpoint*

Essa chamada de API REST usa o método e o endpoint a seguir.

|===


| *Método HTTP* | *Caminho* 


| POST | /api/v1 
|===
*Tipo de processamento*

Assíncrono

*Curl exemplo*

/api/v1/vcenters/ /vcguid/migration-jobs

* JSON input example* corpo de solicitação para migração de 9,12 e 9,13:

selecione "otv_ip": "10.12.13.45", "vasa_provider_credentials": "username": "vasauser", "password": "**********" "database_password": "*************"

Corpo de solicitação para outra migração de liberação:

selecione "otv_ip": "10.12.13.45", "vasa_provider_credentials": "username": "vasauser", "password": "********"

* Exemplo de saída JSON*

Um objeto de tarefa é retornado. Você deve salvar o identificador do trabalho para usá-lo na próxima etapa.

[id]: 123, "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35", "status": "running"

====
. Use o seguinte URI para verificar o status:
+
[listing]
----
https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobID>?includeSubJobsAndTasks=true
----
+
Quando o trabalho estiver concluído, valide o relatório de migração. O relatório faz parte dos dados do trabalho e pode ser visto a partir da resposta do trabalho.

. Adicione as ferramentas do ONTAP para o provedor de storage do VMware vSphere ao vCenter Server e link:../configure/registration-process.html["Registre o provedor VASA com uma instância do vCenter Server"]ao .
. Pare as ferramentas do ONTAP para o provedor de armazenamento VMware vSphere 9,10/9,11/9,12/9,13 Serviço do provedor VASA a partir do console de manutenção.
+
Não elimine o fornecedor VASA.

+
Depois que o antigo provedor VASA é interrompido, o vCenter Server faz failover para as ferramentas do ONTAP para VMware vSphere. Todos os armazenamentos de dados e VMs ficam acessíveis e são servidos a partir das ferramentas do ONTAP para VMware vSphere.

. Execute a migração de patches usando a seguinte API:
+
[]
====
*Método HTTP e endpoint*

Essa chamada de API REST usa o método e o endpoint a seguir.

|===


| *Método HTTP* | *Caminho* 


| PATCH | /api/v1 
|===
*Tipo de processamento*

Assíncrono

*Curl exemplo*

PATCH "/API/v1/vcenters/56d373bd-4163-44f9-a872-9adabb008ca9/migration-jobs/84dr73bd-9173-65R7-w345-8ufdbb887d43

* Exemplo de entrada JSON*

[id]: 123, "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35", "status": "running"

* Exemplo de saída JSON*

Um objeto de tarefa é retornado. Você deve salvar o identificador do trabalho para usá-lo na próxima etapa.

[id]: 123, "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35", "status": "running"

O corpo da solicitação está vazio para operação de patch.


NOTE: uuid é a migração uuid retornada na resposta da API pós migração.

Depois que a API de migração de patches for executada com sucesso, todas as VMs estarão em conformidade com a política de armazenamento.

====
+
Após a migração bem-sucedida e depois de Registrar as ferramentas do ONTAP 10,3 no vCenter Server, faça o seguinte:

+
** Atualize o certificado em todos os hosts.
** Aguarde algum tempo antes de executar operações de datastore (DS) e Virtual Machine (VM). O tempo de espera depende do número de hosts, DS e VMs na configuração. Quando você não espera, as operações podem falhar intermitentemente.




*Depois de terminar*

Após a atualização, se o estado de conformidade da máquina virtual estiver desatualizado, reaplique a política de armazenamento da máquina virtual usando as seguintes etapas:

. Navegue até o datastore e selecione *Summary* > *VM Storage Policies*.
+
Em *conformidade com a política de armazenamento de VM*, você pode ver o status de conformidade. Mostra como *desatualizado*

. Selecione a política Storage VM e a VM correspondente
. Selecione *aplicar*
+
O status de conformidade em *conformidade com a política de armazenamento de VM* agora é mostrado como compatível.



*Informações relacionadas*

link:../upgrade/upgrade-ontap-tools.html["Atualize das ferramentas do ONTAP para o VMware vSphere 10.x para o 10,3"]
