---
permalink: protect/configure-storage-replication-adapter-for-san-environment.html 
sidebar: sidebar 
keywords:  
summary: 'Você deve configurar os sistemas de armazenamento antes de executar o Storage Replication Adapter (SRA) para o VMware Live Site Recovery.' 
---
= Configurar o SRA para ambientes SAN e nas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve configurar os sistemas de armazenamento antes de executar o Storage Replication Adapter (SRA) para o VMware Live Site Recovery.



== Configurar o SRA para ambientes SAN

.Antes de começar
Você deve ter os seguintes programas instalados no site protegido e no site de recuperação:

* Recuperação do VMware Live Site
+
A documentação sobre a instalação do VMware Live Site Recovery está no site da VMware.

+
https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/about-vmware-live-site-recovery-installation-and-configuration.html["Sobre o VMware Live Site Recovery"]

* SRA
+
O adaptador é instalado no VMware Live Site Recovery.



.Passos
. Verifique se os hosts ESXi primários estão conetados aos LUNs no sistema de armazenamento primário no local protegido.
. Verifique se os LUNS estão em grupos que têm a `ostype` opção definida como _VMware_ no sistema de armazenamento primário.
. Verifique se os hosts ESXi no local de recuperação têm conetividade iSCSI adequada à máquina virtual de armazenamento (SVM). Os hosts ESXi do local secundário devem ter acesso ao armazenamento do local secundário e os hosts ESXi do local principal devem ter acesso ao armazenamento do local primário.
+
Você pode fazer isso verificando se os hosts ESXi têm LUNs locais conetados na SVM ou o comando nas SVMs `iscsi show initiators`. Verifique o acesso LUN para os LUNs mapeados no host ESXi para verificar a conetividade iSCSI.





== Configurar o SRA para ambientes nas

.Antes de começar
Você deve ter os seguintes programas instalados no site protegido e no site de recuperação:

* Recuperação do VMware Live Site
+
A documentação sobre a instalação do VMware Live Site Recovery pode ser encontrada no site da VMware.

+
https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/about-vmware-live-site-recovery-installation-and-configuration.html["Sobre o VMware Live Site Recovery"]

* SRA
+
O adaptador é instalado no VMware Live Site Recovery e no servidor SRA.



.Passos
. Verifique se os datastores no site protegido contêm máquinas virtuais registradas no vCenter Server.
. Verifique se os hosts ESXi no local protegido montaram os volumes de exportações NFS da máquina virtual de storage (SVM).
. Verifique se endereços válidos, como o endereço IP, nome do host ou FQDN em que as exportações NFS estão presentes, estão especificados no campo *endereços NFS* ao usar o assistente Array Manager para adicionar arrays ao VMware Live Site Recovery.
. Use o `ping` comando em cada host ESXi no local de recuperação para verificar se o host tem uma porta VMkernel que pode acessar os endereços IP usados para atender às exportações NFS do SVM.

