---
permalink: protect/map-resource.html 
sidebar: sidebar 
keywords:  
summary: Você deve mapear seus recursos no site protegido e no site de recuperação para que as máquinas virtuais sejam configuradas para fazer failover em um grupo de hosts ou outro. 
---
= Configurar mapeamentos de recursos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve mapear seus recursos no site protegido e no site de recuperação para que as máquinas virtuais sejam configuradas para fazer failover em um grupo de hosts ou outro.

.Antes de começar
Você deve ter conetado os sites protegidos e de recuperação.


NOTE: No VMware Live Site Recovery, os recursos podem ser pools de recursos, hosts ESXi ou clusters vSphere.

.Passos
. Inicie sessão no vCenter Server e selecione *Site Recovery* > *Sites*.
. Selecione seu site protegido e selecione *Gerenciar*.
. Selecione *Mapeamentos de recursos* > *novo* na guia gerenciar para criar um novo mapeamento de recursos.
. No assistente criar mapeamento de recursos, execute o seguinte:
+
.. Selecione *Prepare automaticamente Mapeamentos para recurso com nomes correspondentes* e selecione *Next*.
.. Selecione os objetos de data center necessários para os sites protegidos e de recuperação e selecione *Adicionar mapeamentos*.
.. Selecione *Next* depois que os mapeamentos forem criados com êxito.
.. Selecione o objeto usado anteriormente para criar mapeamento reverso e selecione *Finish*.




.Resultado
A página Mapeamentos de recursos exibe os recursos do site protegido e os recursos do site de recuperação. Você pode seguir os mesmos passos para outras redes em seu ambiente.
