---
permalink: protect/map-network.html 
sidebar: sidebar 
keywords:  
summary: Você deve mapear suas redes no site protegido e no site de recuperação para permitir a comunicação entre elas. 
---
= Configurar mapeamentos de rede
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve configurar seus mapeamentos de recursos, como redes de VM, hosts ESXi e pastas em ambos os sites, para habilitar o mapeamento de cada recurso do site protegido para o recurso apropriado no site de recuperação.

Você deve concluir as seguintes configurações de recursos:

* Mapeamentos de rede
* Mapeamentos de pastas
* Mapeamentos de recursos
* Datastores de espaço reservado


.Antes de começar
Você deve ter conetado os sites protegidos e de recuperação.

.Passos
. Inicie sessão no vCenter Server e selecione *Site Recovery* > *Sites*.
. Selecione seu site protegido e selecione *Gerenciar*.
. Selecione *Mapeamentos de rede* > *novo* na guia gerenciar para criar um novo mapeamento de rede.
. No assistente criar mapeamento de rede, faça o seguinte:
+
.. Selecione *Prepare automaticamente Mapeamentos para redes com nomes correspondentes* e selecione *Next*.
.. Selecione os objetos de data center necessários para os sites protegidos e de recuperação e selecione *Adicionar mapeamentos*.
.. Selecione *Next* depois que os mapeamentos forem criados com êxito.
.. Selecione o objeto usado anteriormente para criar mapeamento reverso e selecione *Finish*.




.Resultado
A página Mapeamentos de rede exibe os recursos do site protegido e os recursos do site de recuperação. Você pode seguir os mesmos passos para outras redes em seu ambiente.
