---
permalink: protect/map-folder.html 
sidebar: sidebar 
keywords:  
summary: Você deve mapear suas pastas no site protegido e no site de recuperação para permitir a comunicação entre elas. 
---
= Configurar mapeamentos de pastas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve mapear suas pastas no site protegido e no site de recuperação para permitir a comunicação entre elas.

.Antes de começar
Você deve ter conetado os sites protegidos e de recuperação.

.Passos
. Inicie sessão no vCenter Server e selecione *Site Recovery* > *Sites*.
. Selecione seu site protegido e selecione *Gerenciar*.
. Selecione *Mapeamentos de pastas* > *pasta* ícone na guia Gerenciar para criar um novo mapeamento de pastas.
. No assistente criar Mapeamento de pastas, execute o seguinte:
+
.. Selecione *Prepare automaticamente Mapeamentos para pastas com nomes correspondentes* e selecione *Next*.
.. Selecione os objetos de data center necessários para os sites protegidos e de recuperação e selecione *Adicionar mapeamentos*.
.. Selecione *Next* depois que os mapeamentos forem criados com êxito.
.. Selecione o objeto usado anteriormente para criar mapeamento reverso e selecione *Finish*.




.Resultado
A página Mapeamentos de pastas exibe os recursos do site protegido e os recursos do site de recuperação. Você pode seguir os mesmos passos para outras redes em seu ambiente.
