---
permalink: protect/update-credentials.html 
sidebar: sidebar 
keywords: SRA credentials, updating 
summary: Para que o VMware Live Site Recovery se comunique com o SRA, você deve atualizar as credenciais do SRA no servidor VMware Live Site Recovery se tiver modificado as credenciais. 
---
= Atualizar credenciais SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para que o VMware Live Site Recovery se comunique com o SRA, você deve atualizar as credenciais do SRA no servidor VMware Live Site Recovery se tiver modificado as credenciais.

.Antes de começar
Você deve ter executado as etapas mencionadas no link:../protect/configure-on-srm-appliance.html["Configurando o SRA no VMware Live Site Recovery Appliance"]tópico .

.Passos
. Execute os seguintes comandos para excluir a pasta da máquina VMware Live Site Recovery senha do nome de usuário das ferramentas do ONTAP em cache:
+
.. `sudo su <enter root password>`
.. `docker ps`
.. `docker exec -it <container_id> sh`
.. `cd conf/`
.. `rm -rf *`


. Execute o comando Perl para configurar o SRA com as novas credenciais:
+
.. `cd ..`
.. `perl command.pl -I --otv-ip <OTV_IP>:8443 --otv-username <OTV_ADMIN_USERNAME> --otv-password <OTV_ADMIN_PASSWORD> --vcenter-guid <VCENTER_GUID>` Você precisa ter uma única cotação em torno do valor da senha.
+
Uma mensagem de sucesso confirmando que as credenciais de armazenamento são armazenadas é exibida. O SRA pode se comunicar com o servidor SRA usando o endereço IP, porta e credenciais fornecidos.




