---
permalink: protect/verify-the-replicated-storage-environment.html 
sidebar: sidebar 
keywords:  
summary: 'Você deve verificar se o site protegido e o site de recuperação estão emparelhados com êxito após configurar o Storage Replication Adapter (SRA). O sistema de storage replicado deve ser detetável tanto pelo local protegido quanto pelo local de recuperação.' 
---
= Verificar sistemas de storage replicados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve verificar se o site protegido e o site de recuperação foram emparelhados com êxito após a configuração do adaptador de replicação de armazenamento (SRA). O sistema de storage replicado deve ser detetável tanto pelo local protegido quanto pelo local de recuperação.

*Antes de começar*

* Você deve ter configurado seu sistema de storage.
* Você deve ter emparelhado o site protegido e o site de recuperação usando o gerenciador de array do VMware Live Site Recovery.
* Você deve ter habilitado a licença FlexClone e a licença SnapMirror antes de executar a operação de failover de teste e a operação de failover para SRA.
* Você deve ter as mesmas políticas e programações do SnapMirror nos sites de origem e destino.


.Passos
. Faça login no vCenter Server.
. Navegue até *Site Recovery* > *Array Based Replication*.
. Selecione o par de matrizes necessário e verifique os detalhes correspondentes.
+
Os sistemas de armazenamento devem ser descobertos no local protegido e no local de recuperação com o Status como ""habilitado"".


