---
permalink: concepts/rbac-learn-about.html 
sidebar: sidebar 
keywords: role based access control, rbac, rbac components, learn about rbac 
summary: 'O controle de acesso baseado em função (RBAC) é uma estrutura de segurança para controlar o acesso a recursos dentro de uma organização. O RBAC simplifica a administração definindo funções com níveis específicos de autoridade para executar ações, em vez de atribuir autorização a usuários individuais. As funções definidas são atribuídas aos usuários, o que ajuda a reduzir o risco de erros e simplifica o gerenciamento do controle de acesso em toda a organização.' 
---
= Saiba mais sobre as ferramentas do ONTAP para VMware vSphere 10 RBAC
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O controle de acesso baseado em função (RBAC) é uma estrutura de segurança para controlar o acesso a recursos dentro de uma organização. O RBAC simplifica a administração definindo funções com níveis específicos de autoridade para executar ações, em vez de atribuir autorização a usuários individuais. As funções definidas são atribuídas aos usuários, o que ajuda a reduzir o risco de erros e simplifica o gerenciamento do controle de acesso em toda a organização.

O modelo padrão RBAC consiste em várias tecnologias de implementação ou fases de complexidade crescente. O resultado é que as implantações reais de RBAC, baseadas nas necessidades dos fornecedores de software e de seus clientes, podem variar de relativamente simples a muito complexas.



== Componentes RBAC

Em alto nível, existem vários componentes que geralmente são incluídos em cada implementação do RBAC. Estes componentes estão ligados de diferentes formas como parte da definição dos processos de autorização.

.Privileges
Um _privilégio_ é uma ação ou capacidade que pode ser permitida ou negada. Pode ser algo simples, como a capacidade de ler um arquivo ou pode ser uma operação mais abstrata específica para um determinado sistema de software. O Privileges também pode ser definido para restringir o acesso a endpoints de API REST e comandos CLI. Cada implementação do RBAC inclui Privileges pré-definido e também pode permitir que os administradores criem Privileges personalizados.

.Funções
Um _role_ é um contentor que inclui um ou mais Privileges. As funções são geralmente definidas com base em tarefas específicas ou funções de trabalho. Quando uma função é atribuída a um usuário, o usuário recebe todos os Privileges contidos na função. E, como acontece com o Privileges, as implementações incluem funções pré-definidas e geralmente permitem que funções personalizadas sejam criadas.

.Objetos
Um _objeto_ representa um recurso real ou abstrato identificado no ambiente RBAC. As ações definidas através do Privileges são executadas em ou com os objetos associados. Dependendo da implementação, o Privileges pode ser concedido a um tipo de objeto ou a uma instância de objeto específica.

.Usuários e grupos
_Users_ são atribuídos ou associados a uma função aplicada após a autenticação. Algumas implementações RBAC permitem que apenas uma função seja atribuída a um usuário, enquanto outras permitem várias funções por usuário, talvez com apenas uma função ativa de cada vez. Atribuir funções a _groups_ pode simplificar ainda mais a administração de segurança.

.Permissões
A _permission_ é uma definição que liga um usuário ou grupo junto com uma função a um objeto. As permissões podem ser úteis com um modelo de objeto hierárquico onde podem ser herdadas opcionalmente pelos filhos na hierarquia.



== Dois ambientes RBAC

Há dois ambientes RBAC distintos que você precisa considerar ao trabalhar com as ferramentas do ONTAP para VMware vSphere 10.

.VMware vCenter Server
A implementação RBAC no VMware vCenter Server é usada para restringir o acesso a objetos expostos por meio da interface de usuário do vSphere Client. Como parte da instalação das ferramentas do ONTAP para VMware vSphere 10, o ambiente RBAC é estendido para incluir objetos adicionais que representam os recursos das ferramentas do ONTAP. O acesso a esses objetos é fornecido através do plug-in remoto. Consulte link:../concepts/rbac-vcenter-environment.html["Ambiente RBAC do vCenter Server"] para obter mais informações.

.Cluster DE ONTAP
As ferramentas do ONTAP para VMware vSphere 10 se conectam a um cluster do ONTAP por meio da API REST do ONTAP para executar operações relacionadas ao storage. O acesso aos recursos de storage é controlado por meio de uma função ONTAP associada ao usuário do ONTAP fornecida durante a autenticação. Consulte link:../concepts/rbac-ontap-environment.html["Ambiente RBAC do ONTAP"] para obter mais informações.
