---
sidebar: sidebar 
permalink: automation/first-call.html 
keywords: ontap tools for vmware vsphere rest api reference, first rest api call, acquire access token 
summary: Você pode emitir uma chamada de API usando o curl para começar a usar as ferramentas do ONTAP para a API REST do VMware vSphere 10. 
---
= Suas primeiras ferramentas do ONTAP para chamada de API REST do VMware vSphere 10
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode emitir uma chamada de API usando o curl para começar a usar as ferramentas do ONTAP para a API REST do VMware vSphere 10.



== Antes de começar

Você deve rever as informações e os parâmetros necessários nos exemplos curl.

.Informações necessárias
Você precisa do seguinte:

* Ferramentas do ONTAP para o endereço IP ou FQDN do VMware vSphere 10, bem como a porta
* Credenciais para o administrador do Gerenciador de ferramentas do ONTAP (nome de usuário e senha)


.Parâmetros e variáveis
Os exemplos de curl apresentados abaixo incluem variáveis de estilo Bash. Você pode definir essas variáveis no ambiente Bash ou atualizá-las manualmente antes de emitir os comandos. Se você definir as variáveis, o shell substituirá os valores em cada comando antes de ser executado. As variáveis são descritas na tabela abaixo.

[cols="25,75"]
|===
| Variável | Descrição 


| FQDN_IP_PORT | O nome de domínio totalmente qualificado ou o endereço IP do Gerenciador de ferramentas do ONTAP juntamente com o número da porta. 


| O PREÇO É DE USD | Nome de usuário para a conta do Gerenciador de ferramentas do ONTAP. 


| MYPASSWORD | Senha associada ao nome de usuário do Gerenciador de ferramentas do ONTAP. 


| ACCESS_TOKEN | O token de acesso emitido pelo Gerenciador de ferramentas do ONTAP. 
|===
Os seguintes comandos e saída na CLI do Linux ilustram como uma variável pode ser definida e exibida:

[listing]
----
FQDN_IP_PORT=172.14.31.224:8443
echo $FQDN_IP
172.14.31.224:8443
----


== Passo 1: Adquira um token de acesso

Você precisa adquirir um token de acesso para usar a API REST. Um exemplo de como solicitar um token de acesso é apresentado abaixo. Você deve substituir os valores apropriados para o seu ambiente.

[source, curl]
----
curl --request POST \
--location "https://$FQDN_IP_PORT/virtualization/api/v1/auth/login” \
--header "Content-Type: application/json" \
--header "Accept: */*" \
-d "{"username": "$MYUSER", "password": "$MYPASSWORD"}"
----
Copie e salve o token de acesso fornecido na resposta.



== Etapa 2: Emita a chamada da API REST

Depois de ter um token de acesso, você pode usar o curl para emitir uma chamada de API REST. Inclua o token de acesso adquirido na primeira etapa.

.Curl exemplo
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP_PORT/virtualization/api/v1/vcenters" \
--header "Accept: */*" \
--header "x-auth: $ACCESS_TOKEN"
----
A resposta JSON inclui uma lista das instâncias do VMware vCenter configuradas para o Gerenciador de ferramentas do ONTAP.
