---
permalink: configure/add-vcenter.html 
sidebar: sidebar 
keywords:  
summary: Adicione instâncias do vCenter Server às ferramentas do ONTAP para o VMware vSphere para configurar, gerenciar e proteger seus datastores virtuais no ambiente do vCenter Server. 
---
= Adicione instâncias do vCenter Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Adicione instâncias do vCenter Server às ferramentas do ONTAP para o VMware vSphere para configurar, gerenciar e proteger seus datastores virtuais no ambiente do vCenter Server.

*Sobre esta tarefa*

Ao integrar-se ao vCenter, as ferramentas do ONTAP permitem que você execute tarefas de storage como provisionamento, snapshots e proteção de dados diretamente do cliente vSphere, eliminando a necessidade de alternar para consoles de gerenciamento de storage separados.

.Passos
. Abra um navegador da Web e navegue até o URL: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Faça login com as ferramentas do ONTAP para as credenciais de administrador do VMware vSphere fornecidas durante a implantação.
. Selecione *vCenters* > *Add* para integrar as instâncias do vCenter Server. Forneça seu endereço IP ou nome de host do vCenter, nome de usuário, senha e detalhes da porta.


Adicionar uma instância do vCenter Server às ferramentas do ONTAP aciona automaticamente as seguintes ações:

* O plug-in do cliente vCenter é registrado como um plug-in remoto.
* Os Privileges personalizados para os plug-ins e APIs são aplicados à instância do vCenter Server.
* Funções personalizadas são criadas para gerenciar os usuários.
* O plug-in aparece como um atalho na interface do usuário do vSphere.

