---
permalink: configure/configure-esx-server-multipath-and-timeout-settings.html 
sidebar: sidebar 
keywords:  
summary: As ferramentas do ONTAP para VMware vSphere verificam e definem as configurações de multipathing do host ESXi e as configurações de tempo limite do HBA que funcionam melhor com os sistemas de armazenamento NetApp. 
---
= Configure as configurações do host ESXi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A configuração das configurações de multipath e timeout do servidor ESXi garante alta disponibilidade e integridade de dados, permitindo alternar perfeitamente para um caminho de armazenamento de backup se um caminho primário falhar.



== Configure as configurações multipath e timeout do servidor ESXi

As ferramentas do ONTAP para VMware vSphere verificam e definem as configurações de multipath do host ESXi e as configurações de tempo limite do HBA que funcionam melhor com os sistemas de armazenamento NetApp.

*Sobre esta tarefa*

Dependendo da configuração e da carga do sistema, esse processo pode levar muito tempo. O progresso da tarefa é exibido no painel tarefas recentes.

.Passos
. Na página inicial do VMware vSphere Web client, selecione *hosts and clusters*.
. Clique com o botão direito do Mouse em um host e selecione *Ferramentas do NetApp ONTAP* > *Atualizar dados do host*.
. Na página de atalhos do cliente da Web VMware vSphere, selecione *Ferramentas do NetApp ONTAP* na seção plug-ins.
. Vá para a placa *ESXi Host Compliance* na visão geral (painel) das ferramentas do ONTAP para o plug-in VMware vSphere.
. Selecione o link *Apply Recommended Settings* (aplicar configurações recomendadas).
. Na janela *Apply Recommended host settings* (aplicar configurações de host recomendadas), selecione os hosts que você deseja atualizar para estar em conformidade com as configurações recomendadas do NetApp e selecione *Next* (Avançar).
+

NOTE: Você pode expandir o host ESXi para ver os valores atuais.

. Na página de definições, selecione os valores recomendados, conforme necessário.
. No painel de resumo, verifique os valores e selecione *Finish*. Você pode acompanhar o progresso no painel de tarefas recentes.




== Defina os valores do host ESXi

Usando as ferramentas do ONTAP para VMware vSphere, você pode definir tempos limite e outros valores nos hosts ESXi para garantir o melhor desempenho e o failover bem-sucedido. Os valores que as ferramentas do ONTAP para VMware vSphere definem são baseados no teste interno do NetApp.

Você pode definir os seguintes valores em um host ESXi:



=== Definições do adaptador HBA/CNA

Define os seguintes parâmetros para valores padrão:

* Disk.QFullSampleSize
* Disk.QFullThreshold
* Tempos limite Emulex FC HBA
* Tempos limite do QLogic FC HBA




=== Definições MPIO

Configurações MPIO definem os caminhos preferidos para sistemas de armazenamento NetApp. Eles determinam quais dos caminhos disponíveis são otimizados (em vez de caminhos não otimizados que atravessam o cabo de interconexão) e definem o caminho preferido para um desses caminhos.

Em ambientes de alto desempenho, ou quando você estiver testando o desempenho com um único armazenamento de dados LUN, considere alterar a configuração de balanceamento de carga da política de seleção de caminho (PSP) de round-robin (VMW_PSP_RR) da configuração padrão de IOPS de 1000 para um valor de 1.



=== Definições NFS

|===


| Parâmetro | Defina este valor para... 


| NET.TcpipHeapSize | 32 


| NET.TcpipHeapMax | 1024 MB 


| NFS.MaxVolumes | 256 


| NFS41.MaxVolumes | 256 


| NFS.MaxQueueDepth | 128 ou superior 


| NFS.HeartbeatMaxFailures | 10 


| Frequência NFS.HeartbeatFrequency | 12 


| NFS.HeartbeatTimeout | 5 
|===