---
permalink: configure/discover-storage-systems-and-hosts.html 
sidebar: sidebar 
keywords:  
summary: Quando você executa pela primeira vez as ferramentas do ONTAP para VMware vSphere em um cliente vSphere, as ferramentas do ONTAP para VMware vSphere descobrem os hosts ESXi, suas exportações de LUNs e NFS, e os sistemas de storage NetApp que possuem esses LUNs e exportações. 
---
= Descubra sistemas de storage e hosts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando você executa pela primeira vez as ferramentas do ONTAP para VMware vSphere em um cliente vSphere, as ferramentas do ONTAP descobrem os hosts ESXi, suas exportações de LUNs e NFS, e os sistemas de storage NetApp que possuem esses LUNs e exportações.

.Antes de começar
* Todos os hosts ESXi devem estar ligados e conetados.
* Todas as máquinas virtuais de armazenamento (SVMs) a serem descobertas devem estar em execução e cada nó de cluster deve ter pelo menos um LIF de dados configurado para o protocolo de armazenamento em uso (NFS ou iSCSI).


*Sobre esta tarefa*

Você pode descobrir novos sistemas de armazenamento ou atualizar informações sobre sistemas de armazenamento existentes para obter as informações mais recentes sobre capacidade e configuração a qualquer momento. Você também pode modificar as credenciais que as ferramentas do ONTAP para VMware vSphere usam para fazer login nos sistemas de storage.

Ao descobrir os sistemas de armazenamento, as ferramentas do ONTAP para VMware vSphere coletam informações dos hosts ESXi gerenciados pela instância do vCenter Server.

.Passos
. Na página inicial do vSphere Client, selecione *hosts and clusters*.
. Clique com o botão direito do rato no centro de dados pretendido e selecione *Ferramentas NetApp ONTAP* > *Atualizar dados do anfitrião* .
+
Na caixa de diálogo *Confirm* (confirmar), confirme a sua escolha.

. Selecione os controladores de armazenamento descobertos que têm o status `Authentication Failure` e selecione *ações* > *Modificar*.
. Preencha as informações necessárias na caixa de diálogo *Modificar sistema de armazenamento*.
. Repita as etapas 4 e 5 para todos os controladores de armazenamento com `Authentication Failure` status.


Depois que o processo de descoberta estiver concluído, execute as seguintes ações:

* Use as ferramentas do ONTAP para VMware vSphere para configurar as configurações do host ESXi para hosts que exibem o ícone de alerta na coluna Configurações do adaptador, na coluna Configurações do MPIO ou na coluna Configurações de NFS.
* Forneça as credenciais do sistema de storage.

