---
permalink: manage/certificate-manage.html 
sidebar: sidebar 
keywords:  
summary: Uma única instância das ferramentas do ONTAP para VMware vSphere pode gerenciar várias instâncias do vCenter Server. As ferramentas do ONTAP para o VMware vSphere são implantadas com um certificado autoassinado para o provedor VASA. Com isso, apenas uma instância do vCenter Server pode ser gerenciada para armazenamentos de dados vVols. 
---
= Gerenciar certificados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um certificado autoassinado é gerado por padrão para as ferramentas do ONTAP e o provedor VASA durante a implantação. Usando a interface do Gerenciador de ferramentas do ONTAP, você pode renovar o certificado ou atualizá-lo para uma CA personalizada. Certificados de CA personalizados são obrigatórios em uma implantação multi-vCenter.

.Antes de começar
* O nome de domínio no qual o certificado é emitido deve ser mapeado para o endereço IP virtual.
* Execute a verificação nslookup no nome de domínio para verificar se o domínio está sendo resolvido para o endereço IP pretendido.
* Os certificados devem ser criados com o nome de domínio e o endereço IP do balanceador de carga.



NOTE: Um endereço IP do loadbalancer deve ser mapeado para um nome de domínio totalmente qualificado (FQDN). Os certificados devem conter o mesmo FQDN mapeado para o endereço IP do balanceador de carga em nomes alternativos de assunto ou assunto.


NOTE: Não é possível alternar de um certificado assinado pela CA para um certificado autoassinado.

[role="tabbed-block"]
====
.Atualize o certificado das ferramentas do ONTAP
--
A guia Ferramentas do ONTAP mostra detalhes como tipo de certificado (autoassinado/CA assinado) e nome de domínio. Durante a implantação, o certificado autoassinado é gerado por padrão. Você pode renovar o certificado ou atualizar o certificado para CA.

.Passos
. Inicie o Gerenciador de ferramentas do ONTAP a partir de um navegador da Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Faça login com as ferramentas do ONTAP para as credenciais de administrador do VMware vSphere fornecidas durante a implantação.
. Selecione *certificados* > *Ferramentas ONTAP* > *renovar* para renovar os certificados.
+
Você pode renovar o certificado se tiver expirado ou estiver próximo da data de validade. A opção renovar está disponível quando o tipo de certificado é assinado pela CA. Na janela pop-up, forneça os detalhes do certificado do servidor, da chave privada, da CA raiz e do certificado intermediário.

+

NOTE: O sistema estará offline até que o certificado seja renovado e você será desconetado da interface do Gerenciador de ferramentas do ONTAP.

. Para atualizar o certificado auto-assinado para certificado CA personalizado, selecione *certificados* > *Ferramentas ONTAP* > *Atualizar para CA* opção.
+
.. Na janela pop-up, carregue o certificado do servidor, a chave privada do certificado do servidor, o certificado da CA raiz e os ficheiros de certificado intermédios.
.. Introduza o nome de domínio para o qual gerou este certificado e atualize o certificado.
+

NOTE: O sistema estará offline até que a atualização esteja concluída, e você será desconetado da interface do Gerenciador de ferramentas do ONTAP.





--
.Atualize o certificado do fornecedor VASA
--
As ferramentas do ONTAP para o VMware vSphere são implantadas com um certificado autoassinado para o provedor VASA. Com isso, apenas uma instância do vCenter Server pode ser gerenciada para armazenamentos de dados vVols. Quando você gerencia várias instâncias do vCenter Server e deseja habilitar o recurso vVols nelas, você precisa alterar o certificado autoassinado para um certificado de CA personalizado.

.Passos
. Inicie o Gerenciador de ferramentas do ONTAP a partir de um navegador da Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Faça login com as ferramentas do ONTAP para as credenciais de administrador do VMware vSphere fornecidas durante a implantação.
. Selecione *certificados* > *Fornecedor VASA* ou *Ferramentas ONTAP* > *renovar* para renovar os certificados.
. Selecione *certificados* > *Fornecedor VASA* ou *Ferramentas ONTAP* > *Upgrade para CA* para atualizar o certificado auto-assinado para certificado CA personalizado.
+
.. Na janela pop-up, carregue o certificado do servidor, a chave privada do certificado do servidor, o certificado da CA raiz e os ficheiros de certificado intermédios.
.. Introduza o nome de domínio para o qual gerou este certificado e atualize o certificado.
+

NOTE: O sistema estará offline até que a atualização esteja concluída, e você será desconetado da interface do Gerenciador de ferramentas do ONTAP.





--
====