---
permalink: manage/edit-appliance-settings.html 
sidebar: sidebar 
keywords:  
summary: Você pode alterar a senha do administrador usando o Gerenciador de ferramentas do ONTAP. 
---
= Alterar as ferramentas do ONTAP para a configuração do VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Usando o Gerenciador de ferramentas do ONTAP, faça a escalabilidade vertical das ferramentas do ONTAP para a configuração do VMware vSphere para aumentar o número de nós na implantação ou alterar a configuração para a configuração de alta disponibilidade (HA). As ferramentas do ONTAP para o dispositivo VMware vSphere são implantadas inicialmente em uma configuração de nó único que não é de HA.

*Antes de começar*

* Certifique-se de que o seu MODELO OVA tem a mesma versão OVA que o nó 1. O nó 1 é o nó padrão em que as ferramentas do ONTAP para o VMware vSphere OVA são implantadas inicialmente.
* Certifique-se de que o hot add e o hot plug de memória da CPU estejam ativados.


.Passos
. Inicie o Gerenciador de ferramentas do ONTAP a partir de um navegador da Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Faça login com as ferramentas do ONTAP para as credenciais de administrador do VMware vSphere fornecidas durante a implantação.
. Selecione *Edit Appliance Settings* (Editar definições do dispositivo) na secção Overview (Descrição geral).
. Na seção *Configuração*, você pode fazer a escalabilidade vertical para aumentar o tamanho do nó e ativar a configuração de HA de acordo com suas necessidades. Você precisa das credenciais do vCenter Server para fazer quaisquer alterações.
+
Quando as ferramentas do ONTAP estão na configuração HA, você pode alterar os detalhes da biblioteca de conteúdo. Você deve fornecer a senha novamente para o novo envio de edição.

+

NOTE: Nas ferramentas do ONTAP para VMware vSphere, você só tem permissão para aumentar o tamanho do nó; não pode reduzir o tamanho do nó. Em uma configuração não HA, apenas uma configuração de tamanho médio é suportada. Em uma configuração de HA, configurações médias e grandes são suportadas.

. Utilize o botão de alternância HA para ativar a configuração HA. Na página *HA settings*, certifique-se de que:
+
** A biblioteca de conteúdo pertence ao mesmo vCenter Server onde as VMs de nó de ferramentas do ONTAP são executadas. As credenciais do vCenter Server são usadas para validar e baixar o modelo OVA para alterações de dispositivo.
** A máquina virtual que hospeda as ferramentas do ONTAP não é implantada diretamente em um host ESXi. A VM deve ser implantada em um cluster ou em um pool de recursos.
+

NOTE: Depois que a configuração de HA estiver ativada, você não poderá reverter para uma configuração de nó único que não seja de HA.



. Na seção *HA settings* da janela *Edit Appliance Settings* (Editar configurações do dispositivo), você pode inserir os detalhes dos nós 2 e 3. As ferramentas do ONTAP para VMware vSphere são compatíveis com três nós na configuração de HA.
+

NOTE: A maioria das opções de entrada são pré-preenchidas com os detalhes da rede do nó 1 para facilitar o fluxo de trabalho. No entanto, você pode editar os dados de entrada antes de navegar para a página final do assistente. Você pode inserir detalhes de endereço IPv6 para os outros dois nós somente quando o endereço IPv6 estiver ativado no primeiro nó.

+
Certifique-se de que um host ESXi contenha apenas uma VM de ferramentas ONTAP. As entradas são validadas cada vez que você passa para a próxima janela.

. Revise os detalhes na seção *Resumo* e *Salvar* as alterações.


.O que se segue?
A página *Visão geral* mostra o status da implantação. Utilizando a ID do trabalho, também pode controlar o estado do trabalho de definições do dispositivo de edição a partir da vista trabalhos.

Se a implantação de HA falhar e o status do novo nó for exibido como "novo", exclua a nova VM no vCenter antes de tentar novamente a operação Habilitar HA.

A guia *Alertas* no painel esquerdo lista alertas de ferramentas do ONTAP para VMware vSphere.
