---
permalink: manage/reset-manager-password.html 
sidebar: sidebar 
keywords:  
summary: Se você Esqueceu a senha do Gerenciador de ferramentas do ONTAP, poderá redefinir as credenciais do administrador usando o token gerado pelas ferramentas do ONTAP para o console de manutenção do VMware vSphere. 
---
= Redefinir a senha do Gerenciador de ferramentas do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você Esqueceu a senha do Gerenciador de ferramentas do ONTAP, poderá redefinir as credenciais do administrador usando o token gerado pelas ferramentas do ONTAP para o console de manutenção do VMware vSphere.

.Passos
. Inicie o Gerenciador de ferramentas do ONTAP a partir de um navegador da Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. No ecrã de início de sessão, selecione a opção *Repor palavra-passe*.
+
Para redefinir a senha do Gerenciador, você precisa gerar o token de redefinição usando as ferramentas do ONTAP para o console de manutenção do VMware vSphere.

+
.. No vCenter Server, abra o console de manutenção
.. Introduza "2" para selecionar a opção System Configuration (Configuração do sistema)
.. Introduza '3' para alterar a palavra-passe do utilizador 'não'.


. Na janela pop-up alterar senha, digite o token de redefinição de senha, o nome de usuário e os detalhes da nova senha.
. Selecione *Reset* para implementar as alterações. Na redefinição bem-sucedida da senha, você pode usar a nova senha para fazer login.

